### ISSUE TITLE
[paser] ParsedComponent vs map[string]string

### ISSUE THREAD

**Issue by kminehart** [openvenues/gopostal#7]
Hi there, I was curious why in `parser` this was done:

```go
type ParsedComponent struct {
    Label string `json:"label"`
    Value string `json:"value"`
}
```

```go
    for i = 0; i < numComponents; i++ {
        parsedComponents[i] = ParsedComponent{
            Label: C.GoString(cLabelsPtr[i]),
            Value: C.GoString(cComponentsPtr[i]),
        }
    }
```

This is pretty hard to use in a practical setting.  I found that the only way I could really use this was to convert it to a `map[string]string` and access it that way.

Wouldn't it be more reasonable to do this?

```go
type PasedComponents map[string]string

// ...
for i = 0; i < numComponents; i++ {
    pasedComponents[C.GoString(cLabelsPtr[i])] = C.GoString(cComponentsPtr[i])
}
```

**Comment by albarrentine** [comment]
Feel free to implement that (these bindings are intentionally very barebones), but there are two issues with having a map as the default response type:

1. It embeds an assumption that libpostal will only return at most one of each component, which is not always the case. Though this is not so common in the US, in some international addresses the structure might look like {house} {unit} {house_number} {road} {house} where the first "house tag" is the venue name and the second is the name of the building or a subdivision. This is quite common in the UK, India, etc. If we used a string-string map, one of the "house" tags would get discarded, so at the very least a map would need to be `map[string][]string`
2. It does not preserve ordering, which can be helpful for people who want to display the address in some way, or want to use some programmatic heuristics to check whether libpostal may have made certain kinds of mistakes in the parse, especially if the user has some prior knowledge about the input.

**Comment by kminehart** [comment]
Oh that's really interesting. I wasn't aware that the labels could be duplicated.

Truthfully, the problem that I have is storing the data returned by `parser.ParseAddress` in a structured database

It seems like my only real option is to unmarshal it and store it in a text field, huh?

Either that, or a `map[string][]string` with a `var keys []string` to store the order of keys, which I don't like for several reasons.

**Comment by albarrentine** [comment]
Sure. So if this is a geocoding application, it's best to parse/normalize the addresses on the way in, store them in a queryable way, parse/normalize the user input in the same way, and run structured queries on one or more fields.

In a full-text search engine like Elasticsearch, the search index handles arrays, etc. and can do all of this for you. In databases, whether relational or non-relational, the same can be accomplished by creating two types of "tables": a doc store and an index.

I'll use MySQL for the purposes of these examples but the same sort of thing will work for any type of RDBMS, full-text search engine, on-disk/distributed key-value store, or even a plain hash table completely in memory.

### Doc store
In a normalized relational db, one option would be something like:

```sql
CREATE TABLE parsed_addresses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    object_id INT,
    address_component VARCHAR(50),
    value VARCHAR(255),
    parse_order INT,
    INDEX (object_id, parse_order)
);
``` 

Assuming here that "object_id" is the unique ID for the records of interest in this schema. From there  a full parse can be retrieved, in order, like so:

```sql
SELECT * FROM parsed_addresses where object_id = ? ORDER BY parse_order
```

Optionally it's also easy to serialize the whole parse and store as a text field since it's really only necessary to query by ID. That would also be the method in a key-value store.

### Inverted nidex

The generic form of an index table would be something like this:

```sql
CREATE TABLE parsed_address_index (
    id INT AUTO_INCREMENT PRIMARY KEY,
    value_type VARCHAR(100),
    value VARCHAR(255),
    object_id INT,
    INDEX (value_type, value)
);
```

Here `value_type` is simply a string but could be an `enum` in an RDBMS, and in key-value stores this is usually part of the key prefix e.g. if value_type="road" and value="main street", the full key might be "road|main street".

Some examples of things that might go in the index table are:

```sql
INSERT INTO parsed_address_index (value_type, value, object_id) VALUES
("house number+road+unit", "123+main street+apt 4", 1),
("house number+road", "123+main street", 1);
```

Using an index table in this way, it's possible to design for any type of queries the application will make. In the above example, the application might first try to search by house number, road, and unit, then by house number and road.

```sql
SELECT object_id FROM parsed_address_index WHERE value_type="house number+road+unit" and value="123+main street+apt 5";
SELECT object_id FROM parsed_address_index WHERE value_type="house number+road" and value="123+main street";
```

With the given sample data, the first query would return no results, and the second query would return object_id 1.

Once you have the candidate object_ids in hand (the index only needs to narrow down the list of possibilities, doesn't need to select 1 and only 1 record), you can select them from the document store and do in-memory tests/perform any necessary ranking.

Note: since the index can effectively map multiple strings to candidate object_ids, it is also a good place to take advantage of libpostal's normalizations through the expand_address API since that handles many different ways of writing street abbreviations in 60 languages, numeric expressions ("1st St", "First St" and "1 St" will all share an expansion), transliteration, unicode normalization, etc.

**Comment by kminehart** [comment]
Perfect.  Thank you so much for that explanation.
